# pnpm-workspace.yaml
packages:
  - '.' # корень проекта (обычно оставляют так)

allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': set this to true or false
  '@prisma/engines': false
  esbuild: true
  prisma: false
  unrs-resolver: true
  vue-demi: set this to true or false

overrides:
  glob: ^13.0.0
  # archiver: ^7.0.1     # можно раскомментировать и попробовать, если нужно
